services:
  jupyter-nb:
    image: jupyter:multi
    container_name: jupyter-mk
    env_file:
      - docker.env
    build: .
    ports:
      - 8888:8888
    volumes:
      - ${HOST_DIR}:/home/nbuser/notebooks
