services:
  jupyter-multi:
    image: jupyter:multi
    container_name: jupyter-mk
    env_file:
      - docker.env
    build: .
    ports:
      - 8888:8888
    volumes:
      - ${HOST_DIR}:/home/jovyan/notebooks

  jupyter-r:
    image: jupyter:r-notebook
    container_name: jupyter-r
    env_file:
      - docker.env
    build:
      context: .
      dockerfile: Dockerfile.R
    ports:
      - 8888:8888
    volumes:
      - ${HOST_DIR}:/home/jovyan/notebooks
